name: build dotnet
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
    paths:
      - dev/dotnet/**
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
jobs:
  push:
    name: "dotnet:${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - '2.1'
          - '2.1-sdk'
          - '3.1'
          - '3.1-sdk'
          - '5.0'
          - '5.0-sdk'
          - '6.0'
          - '6.0-sdk'
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
        with:
          version: "v0.9.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          context: ./dev/dotnet
          file: ./dev/dotnet/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/goover/dotnet:${{ matrix.tag }}
